IndecisiveEaters/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.loginreg.urls", namespace = "login")),
    url(r'^IndecisiveEaters', include("apps.Eaters.urls", namespace = "Eaters")),
]

apps/Eaters/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name= 'index'),
	url(r'^favorites$', views.favorites, name= 'favorites'),
	url(r'^add$', views.add, name= 'add'),
]

apps/loginreg/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name= 'index'),
    url(r'^register', views.register, name= 'register'),
    url(r'^login', views.login, name='login'),
	url(r'^logout', views.logout, name='logout')
	]

apps/Eaters/models.py
from __future__ import unicode_literals
from ..loginreg.models import User
from django.db import models

# Create your models here.
class Eater(models.Model):
    restaurant = models.TextField(max_length = 50)
    address = models.TextField(max_length = 50)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    user = models.ForeignKey(User)

apps/loginreg/models.py
from __future__ import unicode_literals
import re, bcrypt
from django.core.exceptions import ObjectDoesNotExist
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    # Create list of errors to be used for validation, initialize as empty list
    def validation_errors(self, request):
        errors = []
        # Check length of first and last names
        if len(request.POST['first_name']) < 2 or len(request.POST['last_name']) < 2:
            errors.append("First and last name must be longer than two characters.")
        # Check that the email is in the correct format
        if not EMAIL_REGEX.match(request.POST['email']):
            errors.append("Must use valid email")
        # Check that password length is long enough, and matches the confirm password
        if len(request.POST['password']) < 8 or request.POST['password'] != request.POST['pwconfirm']:
            errors.append("Passwords must match and be at least 8 characters")
        # Return the list of errors in a list, to be displayed on the main page
        return errors

    def reg_validation(self, request):
        # Refer back to the validation_error function
        errors = self.validation_errors(request)
        # If there are any errors, return those errors instead of moving on
        if len(errors) > 0:
            return (False, errors)
        # If there are no errors, hash the password using Bcrypt, then add user to database
        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
        user = self.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], pw_hash=pw_hash)
        return (True, user)

    def login_validation(self, request):
        # Check if user email and password are in database, and if they match
        try:
            user = User.objects.get(email=request.POST['email'])
            password = request.POST['password'].encode()
            if bcrypt.hashpw(password, user.pw_hash.encode()) == user.pw_hash:
                return (True, user)
        # If neither exist, just return false automatically. If one of these returns false, return the same result to keep confidentiality
        except ObjectDoesNotExist:
            pass
        return (False, ["Email/password don't match those in the database"])

class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=60)
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/Eaters/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "Eaters/index.html")

def add(request):
    pass

def favorites(request):
    return render(request, "Eaters/favorites.html")

apps/loginreg/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from django.contrib import messages

def index(request):
    return render(request, 'loginreg/index.html')

def register(request):
    # Return the resulting errors back from models as a stored variable
    result = User.objects.reg_validation(request)
    # If there are errors, display the error messages after redirecting to the main page
    if result[0] == False:
        print_messages(request, result[1])
        return redirect('/')
    # Otherwise, if there are no errors, sent the registered info to the login_success function
    return login_success(request, result[1])

def login(request):
    # Return the resulting errors back from models as a stored variable
    result = User.objects.login_validation(request)
    # If there are errors, display the error messages after redirecting to the main page
    if result[0] == False:
        print_messages(request, result[1])
        return redirect('/')
    # Otherwise, if there are no errors, sent the registered info to the login_success function
    return login_success(request, result[1])

def login_success(request, user):
    # Store all the login information of the logged-in user in session, then redirect them to the success page
    request.session['user'] = {
        'id' : user.id,
        'first_name' : user.first_name,
        'last_name' : user.last_name,
        'email' : user.email,
    }
    return redirect ('Eaters:index')

def print_messages(request, message_list):
    # For any error messages, add them to the error message list to be displayed on the HTML pages
    for message in message_list:
        messages.add_message(request, messages.INFO, message)


def logout(request):
    # Knock the current user out of session
    request.session.pop('user')
    return redirect('/')

apps/Eaters/templates/Eaters/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Indecisive Eaters</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <style type="text/css">
        #map {
            height: 50%;
            width: 50%;
        }
        html, body {
          height: 100%;
          margin: 0;
          padding: 0;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAC7hoqTltP1b-i3FEjacejkPn081QFbQ&libraries=places&callback=initMap"></script>
    <script>
      var map;
      var infoWindow;
      function initMap() {
        infoWindow = new google.maps.InfoWindow();
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: position.coords.latitude, lng: position.coords.longitude},
              zoom: 15
            });

            var service = new google.maps.places.PlacesService(map);
            service.nearbySearch({
              location: map.center,
              radius: 1600,
              type: ['restaurant']
            },callback);
          },
          function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        }
        else {
          map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 47.610141, lng: -122.196575},
            zoom: 15
          });
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

    function callback(results, status) {
      if (status === google.maps.places.PlacesServiceStatus.OK) {
        for (var i = 0; i < results.length; i++) {
          createMarker(results[i]);
        }
      }
    }

    function createMarker(place) {
      var placeLoc = place.geometry.location;
      var marker = new google.maps.Marker({
        map: map,
        position: place.geometry.location
      });

      google.maps.event.addListener(marker, 'click', function() {
        infoWindow.setContent(place.name + ": " + place.vicinity);
        infoWindow.open(map, this);
      });
    }
    </script>
</head>
<body>
    <a href="{% url 'login:logout' %}">Logout</a>
    <h1>Indecisive Eaters</h1>
    <label>Can't figure what you want to eat? Say no more...</label>
    <div id="map">

    </div>

    <form class="" action="" method="post">
        {% csrf_token %}
        <input type="submit" name="Random" value="Random Generator">
    </form>
</body>
</html>

apps/loginreg/templates/loginreg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <title>Login and Registration</title>

    <style>
        h1 {
            font-family: monaco, Consolas, "Lucida Console", monospace;
        }

        #register{
            display: inline-block;
        }
        #login{
            display: inline-block;
            vertical-align: top;
            margin-left: 100px;
        }
    </style>
</head>
<body>
    <h1>Indecisive Eaters</h1>
    <div id="register">
        <h4>Registration</h4>
        <form action="/register" method='post'>
            {% csrf_token %}
            <label>First Name:</label>
            <input type="text" name='first_name'><br>
            <label>Last Name:</label>
            <input type="text" name='last_name'><br>
            <label>Email:</label>
            <input type="text" name='email'><br>
            <label>Password:</label>
            <input type="password" name='password'><br>
            <label>Confirm Password:</label>
            <input type="password" name='pwconfirm'><br>
            <input type="submit" class='pagebutton' value='Register'>
        </form>
    </div>
    <div id="login">
            <h4>Login</h4>
            <form action="login" method='post'>
                {% csrf_token %}
                <label>Email:</label>
                <input type="text" name='email'><br>
                <label>Password:</label>
                <input type="password" name='password'><br>
                <input type="submit" class='pagebutton' value='Login'>
            </form>
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </div>
</body>
</html>

apps/loginreg/templates/loginreg/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css"> -->
    <title>Success Page</title>
</head>
<body>
    <div>

        <h1>Great Success!</h1>
        <p>You did it! You totally logged in, {{request.session.user.first_name}}.</p>
        <form action="/logout">
            <input type="submit" value='Log Out'>
        </form>
    </div>
</body>
</html>